export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Work_Sans } from "next/font/google";
const worksans = Work_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={worksans.className}>{children}</body>
    </html>
  );
}
